export const pages = [
  {
    N: "Home",
    id: "home",
    parentId: null,
    nicename: "",
    type: "home",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Grid",
    id: "grid",
    parentId: null,
    nicename: "grid",
    type: "grid",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Global elements",
    id: "global-elements",
    parentId: null,
    nicename: "global-elements",
    type: "global-elements",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Forms",
    id: "forms",
    parentId: null,
    nicename: "forms",
    type: "forms",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Input types",
    id: "input-types",
    parentId: "forms",
    nicename: "input-types",
    type: "input-types",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Form wizard",
    id: "form-wizard",
    parentId: null,
    nicename: "form-wizard",
    type: "form-wizard",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Results",
    id: "results",
    parentId: null,
    nicename: "results",
    type: "results",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Messages",
    id: "messages",
    parentId: null,
    nicename: "messages",
    type: "messages",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Tabs",
    id: "tabs",
    parentId: null,
    nicename: "tabs",
    type: "tabs",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Slider",
    id: "slider",
    parentId: null,
    nicename: "slider",
    type: "slider",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Modals",
    id: "modals",
    parentId: null,
    nicename: "modals",
    type: "modals",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Buttons",
    id: "buttons",
    parentId: null,
    nicename: "buttons",
    type: "buttons",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Wysiwyg",
    id: "wysiwyg",
    parentId: null,
    nicename: "wysiwyg",
    type: "wysiwyg",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Calendar",
    id: "calendar",
    parentId: null,
    nicename: "calendar",
    type: "calendar",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Accordions",
    id: "accordions",
    parentId: null,
    nicename: "accordions",
    type: "accordions",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Notifications",
    id: "notifications",
    parentId: null,
    nicename: "notifications",
    type: "notifications",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
  {
    N: "Date picker",
    id: "date-picker",
    parentId: null,
    nicename: "date-picker",
    type: "date-picker",
    showInNav: true,
    showInSecondaryNav: true,
    isPrivate: false,
    profilesAllowed: 1,
  },
];
